project:
  type: website
  output-dir: docs

website:
  title: "Jordan Ischard's page"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: work.qmd
        text: Work
      - href: teaching.qmd
        text: Teaching
      - href: resume.qmd
        text: Resume
  page-footer: 
    left: "Copyright 2025, Jordan Ischard" 
    right:
      - icon: github
        href: https://github.com/JordanIschard
      - icon: linkedin
        href: https://www.linkedin.com/in/jordan-ischard-040a69173/

format:
  html:
    theme:
      # - default

      - united
      
      # - minty
      
      # - cosmo
      # - brand
    css: styles.css
    toc: true



